name: bayes-opt

services:

  jupyter-nb:
    image: bayes-opt
    build:
      context: .
      dockerfile: gpflow_R.Dockerfile
    ports:
      - 8889:8888
    volumes:
      - type: bind
        source: ..
        target: /tf
    command: sh -c "jupyter notebook --notebook-dir=/tf --ip 0.0.0.0 --no-browser --allow-root"

  marimo-nb:
    image: bayes-opt
    ports:
      - 8080:8080
    volumes:
      - type: bind
        source: ..
        target: /tf
    command: sh -c "marimo edit --host 0.0.0.0 --port 8080 --headless --no-token"
    