name: gpflow-trieste-r

services:
  tensorflow:
    build:
      context: .
      dockerfile: gpflow_R.Dockerfile
    ports:
      - 8889:8888
    volumes:
      - type: bind
        source: ..
        target: /tf
    