[build-system]
requires = ["setuptools >= 77.0.3"]
build-backend = "setuptools.build_meta"

[project]
name = "py_group_sequential_designs"
version = "0.0.1"
authors = [
  { name="Mazin Abdelghany", email="me@exam.com" },
]
description = "Package with functions for group sequential design generation and Bayesian optimization loop"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "numpy",
    "pandas",
    "scipy"
]
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]
license = "MIT"
license-files = ["LICEN[CS]E*"]

[project.urls]
Homepage = "https://github.com/mazin-abdelghany/phd-bayesopt-esd/pyGroupSequentialDesigns/"
Issues = "https://github.com/mazin-abdelghany/phd-bayesopt-esd/pyGroupSequentialDesigns/issues"
