#include <iostream>
#include <cmath>
#include <fstream>
#include <iomanip>
#include <cstdio>
#include <cstdlib> 
#include <vector>
#include <ctime>

// Wichmann–Hill uniform pseudorandom number generator
// Wichmann, Brian A.; Hill, I. David (1982). "Algorithm AS 183: An Efficient 
// and Portable Pseudo-Random Number Generator". Journal of the Royal 
// Statistical Society. Series C (Applied Statistics). 
double uniform_random_01()
{
    static long ix{1};
    static long iy{1};
    static long iz{1};

    double r{};
  
    ix = (171*ix) % 30269;
    iy = (172*iy) % 30307;
    iz = (170*iz) % 30323;

    r  = static_cast<double>(ix)/30269.
         + static_cast<double>(iy)/30307. 
         + static_cast<double>(iz)/30323.;

    return r - static_cast<int>(r);
}

// can use the mersenne twister implemented in C++ standard library:
// would need to #include <random>
// void mersenne_twister()
// {
//     std::random_device rd;  // Will be used to obtain a seed for the random number engine
//     std::mt19937 gen(rd()); // Standard mersenne_twister_engine seeded with rd()
//     std::uniform_real_distribution<> dis(0., 1.);
//     for (int n = 0; n < 10; ++n)
//         // Use dis to transform the random unsigned int generated by gen into a 
//         // double in [1, 2). Each call to dis(gen) generates a new random double.
//         std::cout << dis(gen) << ' ';
//     std::cout << '\n';
// }

// finds normal pdf, cdf and inverse cdf
double normal_pdf(double z)
{
    return ((1.)/sqrt(2*M_PI)) * exp((-z*z)/2);
}

// Abramowitz & Stegun (1964) approximation 
// of the standard normal cdf accurate to < 7.5e-8 based on
// Abramowitz/Stegun 26.2.17
// maybe originally in  Approximations for Digital Computers
// Cecil Hastings 1955
double normal_cdf(double z)
{
    if (z > 6.0)
    {
        return 1.0;
    }
  
    if (z < -6.0)
    {
        return 0.0;
    }

    double b1 {0.31938153};
    double b2 {-0.356563782};
    double b3 {1.781477937};
    double b4 {-1.821255978};
    double b5 {1.330274429};

    double p {0.2316419};

    // numerical approximation for 1/sqrt(2*pi)
    double c2 {0.3989423};

    double a = fabs(z);
    double t = 1.0/(1.0+a*p);

    // the below calculation is equivalent to:
    // 1 - 1/sqrt(2*pi) * exp( -(pow(z,2)/2) ) * ( b1*t + b2*pow(t,2.0) 
    //                                             + b3*pow(t,3.0) + b4*pow(t,4.0) 
    //                                             + b5*pow(t,5.0) )
    double b = c2*exp((-z)*(z/2.0));
    double n = ((((b5*t+b4)*t+b3)*t+b2)*t+b1)*t;

    n = 1.0 - b*n;

    if (z < 0.0) 
    {
        n = 1.0 - n;
    }

    return n;
}

// pulled from: https://web.archive.org/web/20151030215612/http://home.online.no/~pjacklam/notes/invnorm/#Computer_implementations
// error is 1.15e-9
// scipy uses a different approximation from W.J. Cody published in AMS
// "Rational Chebyshev approximations for the error function" by W. J. Cody
// https://www.ams.org/journals/mcom/1969-23-107/S0025-5718-1969-0247736-4/S0025-5718-1969-0247736-4.pdf
// maximal relative error is 6e-19 to 3e-20
double inverse_normal_cdf(double p)
{
    double  A1 {-3.969683028665376e+01};
    double  A2 {2.209460984245205e+02};
    double  A3 {-2.759285104469687e+02};
    double  A4 {1.383577518672690e+02};
    double  A5 {-3.066479806614716e+01};
    double  A6 {2.506628277459239e+00};

    double  B1 {-5.447609879822406e+01};
    double  B2 {1.615858368580409e+02};
    double  B3 {-1.556989798598866e+02};
    double  B4 {6.680131188771972e+01};
    double  B5 {-1.328068155288572e+01};

    double  C1 {-7.784894002430293e-03};
    double  C2 {-3.223964580411365e-01};
    double  C3 {-2.400758277161838e+00};
    double  C4 {-2.549732539343734e+00};
    double  C5 {4.374664141464968e+00};
    double  C6 {2.938163982698783e+00};

    double  D1 {7.784695709041462e-03};
    double  D2 {3.224671290700398e-01};
    double  D3 {2.445134137142996e+00};
    double  D4 {3.754408661907416e+00};

    double P_LOW {0.02425};
    double P_HIGH {0.97575};

    double x{};
    double q{};
    double r{};
    double u{};
    double e{};

    if (0 < p && p < P_LOW)
    {
        q = sqrt(-2*log(p));
        x = (((((C1*q+C2)*q+C3)*q+C4)*q+C5)*q+C6) / ((((D1*q+D2)*q+D3)*q+D4)*q+1);
    }
  
    else if (P_LOW <= p && p <= P_HIGH)
    {
        q = p - 0.5;
        r = q*q;
        x = (((((A1*r+A2)*r+A3)*r+A4)*r+A5)*r+A6)*q /(((((B1*r+B2)*r+B3)*r+B4)*r+B5)*r+1);
    }

    else if (P_HIGH < p && p < 1) 
    {
        q = sqrt(-2*log(1-p));
        x = -(((((C1*q+C2)*q+C3)*q+C4)*q+C5)*q+C6) / ((((D1*q+D2)*q+D3)*q+D4)*q+1);
    }

    // The relative error of the approximation has absolute value less than 
    // 1.15e−9.  One iteration of Halley’s rational method (third order) gives
    // full machine precision.
    // restricted to the range if 0 to 1 because the above correctly estimates
    // the values at 0 and 1 while the below "correction" fails.
    if (0 < p && p < 1) 
    {
        e = 0.5 * erfc(-x/sqrt(2)) - p;
        u = e * sqrt(2*M_PI) * exp(x*x/2);
        x = x - u/(1 + x*u/2);
    }
  
    return x;
}

// finds K-stage triangular design for given design parameters. The resulting 
// design is put in the vector parameters 
void find_triangular_design(
        double delta0,
        double delta1,
        double sigma,
        double K,
        double required_alpha,
        double required_beta,
        std::vector<double>& parameters)
{
    // used to calculate delta_tilde
    double inv_norm_cdf_alpha = inverse_normal_cdf(1 - required_alpha);
    double inv_norm_cdf_beta = inverse_normal_cdf(1 - required_beta);

    // correction for delta to achieve required alpha and beta (delta_tilde)
    // from Wason 2018 paper
    double delta_tilde = (2*inv_norm_cdf_alpha) / (inv_norm_cdf_alpha + inv_norm_cdf_beta); 
    
    double delta = delta_tilde * (delta1 - delta0);

    // calculating maximum information by splitting the terms
    double Imax_term1 = (4. * pow(0.583, 2.))/K;
    double Imax_term2 = 8. * log(1./(2. * required_alpha));
    double Imax_term3 = (2. * 0.583)/sqrt(K);

    double Imax = pow(sqrt(Imax_term1 + Imax_term2) - Imax_term3, 2.) / pow(delta, 2.);

    // finding the number of individuals per stage
    int num_indiv_per_stage = static_cast<int>(ceil(Imax*2*sigma*sigma/K));
    
    // create a vector for collecting the cumulative sample size 
    std::vector<double> cumu_sample_size;
    cumu_sample_size.push_back(num_indiv_per_stage);
   
    // fills a vector that contains number of individuals total, e.g.,
    // if num_indiv_per_stage = 20, and there are 3 stages, this generates a
    // vector called cumulative sample size = {20, 40, 60}
    // here i is size_t because we are indexing the vector below
    for(size_t i = 1; i < static_cast<size_t>(K); i++)
    {
        cumu_sample_size.push_back(
            num_indiv_per_stage + cumu_sample_size.at(i-1)
        );
    }

    parameters.clear();

    // the first parameter in vector is the number of individuals per stage
    // calculated above using information
    parameters.push_back(num_indiv_per_stage);

    double information{};
    double c{}; // lower bounds
    double d{}; // upper bounds

    // here i is double because it is being used to calculate information 
    // fraction
    for(double i = 0; i < K; i++)
    {
        // calculate the bounds on the score scale
        c=-(2.0/delta)*log(1.0/(2*required_alpha))+0.583*sqrt(Imax/K)+(3*delta/4)*((i+1)/K)*Imax;
        d=(2.0/delta)*log(1.0/(2*required_alpha))-0.583*sqrt(Imax/K)+(delta/4)*((i+1)/K)*Imax;
        
        // using the information at the current stage, convert the bounds to 
        // the standardized z scale
        information=Imax*((i+1)/K);
        parameters.push_back(c/sqrt(information));
        parameters.push_back(d/sqrt(information));
        
    }

}

// finds the sample size required for a one-stage trial with 
// given design parameters
double one_stage_sample_size(
        double difference,
        double sigma,
        double typeIerror,
        double typeIIerror,
        double R)
{
    // ratio of smaller group to larger group
    double r = (1+R)/R;

    // z statistic for alpha
    double z_alpha = inverse_normal_cdf(1-typeIerror);

    // z statistic for power
    double z_power = inverse_normal_cdf(1-typeIIerror);
    
    return r * ((pow(sigma, 2) * pow(z_alpha + z_power, 2))/(difference*difference));
}

// calculates the information given number of individuals and sigma:
double information(double num_individuals, double sigma)
{
  return num_individuals/(2*sigma*sigma);
}

double expected_sample_size(
        std::vector<double> phi,
        std::vector<double> psi,
        std::vector<double> parameters)
{
    double expected_sample_size {0};
    double n_per_stage = parameters.at(0);

    // separating indexing vector with multiplication without loop by 
    // initializing a new variable mult
    double mult = 1;
    for(size_t i = 0; i < phi.size(); i++)
    {
        // based on expected sample size equation, suspect that:
        // phi is the probability of stopping for efficacy and
        // psi is the probability of stopping for futility 
        expected_sample_size += mult * n_per_stage * (phi.at(i)+psi.at(i));
        mult++;
    }

    return expected_sample_size;
}

void converthtopsi(
        std::vector<std::vector<double>>& h,
        std::vector<std::vector<double>>& z,
        std::vector<double>& psi,
        std::vector<double>& parameters,
        double delta0,
        double new_delta,
        double sigma)
{
    double i{};
    size_t j{};

    psi.clear();

    psi.push_back(
        normal_cdf(parameters.at(1)
                   - new_delta * sqrt(parameters.at(0))/sqrt(2*sigma*sigma))
    );

    for (i = 1; i <= static_cast<double>(z.size()); i++)
    {
        psi.push_back(0);
    
        for (j = 0; 
             j < z.at(static_cast<size_t>(i)-1).size(); 
             j++)
        {
            // this calculation is the same as the below in convert to phi with
            // two minor differences
            psi.at(static_cast<size_t>(i))
                // equation ell(z_k, I_k | theta_2, theta_1) near equation 19.13    
                += exp((new_delta-delta0)*z.at(static_cast<size_t>(i)-1).at(j)*sqrt(information(i*parameters.at(0),sigma))
                - (pow(new_delta,2)-pow(delta0,2))
                * information(i*parameters.at(0),sigma)/2)
                // equation h_k-1(i_k-1 | theta1)
                * (h.at(static_cast<size_t>(i)-1).at(j)
                // this is e_k-1(z_k-1(i_k-1)), b_k | theta2)
                // except 1- is at the front
                * (1 - normal_cdf(
                    (z.at(static_cast<size_t>(i)-1).at(j)*sqrt(information(i*parameters.at(0),sigma))
                    // term 1 of eqution 19.6 except we are indexing the odd value
                    // here we have (i+1)*2-1 rather than (i+1)*2
                    - parameters.at(static_cast<size_t>((i+1)*2-1))*sqrt(information((i+1)*parameters.at(0),sigma))
                    // term 2 of equation 19.6
                    + new_delta * (information((i+1)*parameters.at(0),sigma)
                        - information(i*parameters.at(0),sigma)))
                    // divided by sqrt(delta_k) in equation 19.6 
                    / (sqrt(information((i+1)*parameters.at(0),sigma) - information(i*parameters.at(0),sigma))))));
        }
    
    }

}

void converthtophi(
        std::vector<std::vector<double>>& h,
        std::vector<std::vector<double>>& z,
        std::vector<double>& phi,
        std::vector<double>& parameters,
        double delta0,
        double new_delta,
        double sigma)
{
    double i;
    size_t j;

    phi.clear();

    phi.push_back(
        1 - normal_cdf(parameters.at(2)
            - new_delta*sqrt(parameters.at(0))/sqrt(2*sigma*sigma))
    );

    for(i = 1; i <= static_cast<double>(z.size()); i++)
    {
        phi.push_back(0);
    
        for(j = 0; j < z.at(static_cast<size_t>(i)-1).size(); j++)
        {
            phi.at(static_cast<size_t>(i)) 
                // equation ell(z_k, I_k | theta_2, theta_1) near equation 19.13    
                += exp((new_delta-delta0)*z.at(static_cast<size_t>(i)-1).at(j)*sqrt(information(i*parameters.at(0),sigma))
                - (pow(new_delta,2)-pow(delta0,2))
                * information(i*parameters.at(0),sigma)/2)
                // equation h_k-1(i_k-1 | theta1)
                * (h.at(static_cast<size_t>(i)-1).at(j)
                // e_k-1(z_k-1(i_k-1)), b_k | theta2)
                // equation 19.6
                * (normal_cdf(
                    // term 1 of equation 19.6
                    (z.at(static_cast<size_t>(i)-1).at(j) * sqrt(information(i*parameters.at(0),sigma))
                    // term 3 of equation 19.6
                    - parameters.at(static_cast<size_t>((i+1)*2))*sqrt(information((i+1)*parameters.at(0),sigma))
                    // term 2 of equation 19.6
                    + new_delta*(information((i+1)*parameters.at(0),sigma)
                        - information(i*parameters.at(0),sigma)))
                    // divided by sqrt(delta_k) in equation 19.6
                    / (sqrt(information((i+1)*parameters.at(0),sigma) - information(i*parameters.at(0),sigma))))));
        }
    
    }

}

// finds the delta which gives highest expected sample size for a given design
void finddeltaminimax_seq(
        std::vector<std::vector<double>>& h,
        std::vector<std::vector<double>>& z,
        std::vector<double>& parameters,
        double delta0,
        double new_delta,
        double sigma,
        double *deltaminimax,
        double *maxen)
{

    double lowerdelta=delta0;
    double middelta=new_delta;
    double upperdelta=delta0+2*(new_delta-delta0);
    double tempdelta;
    double loweren;
    double miden;
    double upperen;
    double tempen;

    std::vector<double> lowerphi;
    std::vector<double> lowerpsi;
    std::vector<double> midphi;
    std::vector<double> midpsi;
    std::vector<double> upperphi;
    std::vector<double> upperpsi;
    std::vector<double> tempphi;
    std::vector<double> temppsi;

    converthtophi(h,z,lowerphi,parameters,delta0,lowerdelta,sigma);
    converthtophi(h,z,midphi,parameters,delta0,middelta,sigma);
    converthtophi(h,z,upperphi,parameters,delta0,upperdelta,sigma);
    converthtopsi(h,z,lowerpsi,parameters,delta0,lowerdelta,sigma);
    converthtopsi(h,z,midpsi,parameters,delta0,middelta,sigma);
    converthtopsi(h,z,upperpsi,parameters,delta0,upperdelta,sigma);

    loweren = expected_sample_size(lowerphi,lowerpsi,parameters);
    miden = expected_sample_size(midphi,midpsi,parameters); 
    upperen = expected_sample_size(upperphi,upperpsi,parameters);

    //check whether miden is higher than both loweren and upperen
    
    while (miden<loweren || miden<upperen)
    {
        lowerdelta-=(new_delta-delta0);
        upperdelta+=(new_delta-delta0);
        converthtophi(h,z,lowerphi,parameters,delta0,lowerdelta,sigma);
        converthtophi(h,z,upperphi,parameters,delta0,upperdelta,sigma);
        converthtopsi(h,z,lowerpsi,parameters,delta0,lowerdelta,sigma);
        converthtopsi(h,z,upperpsi,parameters,delta0,upperdelta,sigma);
        loweren=expected_sample_size(lowerphi,lowerpsi,parameters);
        upperen=expected_sample_size(upperphi,upperpsi,parameters);
    }
    
    //find delta which gives maximum expected sample size:
    while((middelta-lowerdelta)>1e-3 || (upperdelta-middelta)>1e-3) 
    {
        if ((upperdelta-middelta)>(middelta-lowerdelta))
        {
            tempdelta=(upperdelta+middelta)/2;
            converthtophi(h,z,tempphi,parameters,delta0,tempdelta,sigma);
            converthtopsi(h,z,temppsi,parameters,delta0,tempdelta,sigma);
            tempen=expected_sample_size(tempphi,temppsi,parameters);
            
            if (tempen<miden)
            {
                upperen=tempen;
                upperdelta=tempdelta;
                upperphi=tempphi;
                upperpsi=temppsi;
            }
            
            else
            {
                loweren=miden;
                lowerdelta=middelta;
                lowerphi=midphi;
                lowerpsi=midpsi;
                miden=tempen;
                middelta=tempdelta;
                midphi=tempphi;
                midpsi=temppsi;
            }
        }
        
        else
        {
            tempdelta=(lowerdelta+middelta)/2;
            converthtophi(h,z,tempphi,parameters,delta0,tempdelta,sigma);
            converthtopsi(h,z,temppsi,parameters,delta0,tempdelta,sigma);
            tempen=expected_sample_size(tempphi,temppsi,parameters);
            
            if(tempen<miden)
            {
                loweren=tempen;
                lowerdelta=tempdelta;
                lowerphi=tempphi;
                lowerpsi=temppsi;
            }
            
            else
            {
                upperen=miden;
                upperdelta=middelta;
                upperphi=midphi;
                upperpsi=midpsi;
                miden=tempen;
                middelta=tempdelta;
                midphi=tempphi;
                midpsi=temppsi;
            }
        }
    }
    
    *deltaminimax=middelta;
    *maxen=miden;

}

// trialproperties_seq uses the method given in Section 19.2 of Jennison and 
// Turnbull (2000) to find the probability of stopping at each stage in a 
// sequential trial using Z-tests
void trialproperties_seq(
        std::vector<double>& parameters,
        double delta0,
        double delta1,
        double sigma,
        double *typeIerror,
        double *power,
        double *expected_sample_size_null,
        double *expected_sample_size_crd,
        double *worstcasedelta,
        double *expected_sample_size_dm,
        int checkdm)
{

    // Function will find typeIerror and power for trial parameters. If 
    // checkdm==1, the worst-case scenario delta will be found together with its 
    // expected sample size. Else, both will be returned as 0
    *worstcasedelta = 0;
    *expected_sample_size_dm = 0;

    size_t i{};
    double j{};

    // this temporary vector will be used throughout all of the below for loops
    // as a placeholder for the actual vector being calculated
    std::vector<double> tempvector;

    // get grid of points to use
    // the grid is x_i with elements {x_1, . . . , x_6r-1} (see immediately 
    // below equation 19.9)
    // r is defined as 16 in the code below
    // Also note that x is a 2 dimensional vector, that can have different 
    // lengths for each dimension, for example:
    // [[1, 2, 3],
    //  [4, 5, 6, 7, 8]]
    // x has the same number of rows as boundary pairs minus 1
    std::vector<std::vector<double>> x;

    // loop through the boudaries
    // parameters.size is one larger than 2*stages because it also contains
    // the sample size within it. Also, subtract 1 because the last boundary
    // is equal in one-stage designs, hence (parameters.size-1)/2-1
    for (i = 0; i < (parameters.size()-1)/2 - 1; i++)
    {
        tempvector.clear();

        // add the first boundary value to the grid of points
        tempvector.push_back(parameters.at(i*2+1));
        
        // initialize mean at each stage
        // mean_at_stage is theta * sqrt(information at each stage)
        double mean_at_stage  = delta0 * sqrt(
            information((static_cast<double>(i)+1)*parameters.at(0),sigma)
        );
        
        // these are the first 15 grid points
        for (j = 1; j <= 15; j++)
        {
            // the following if statements check to see if the value of the 
            // next grid point is between the two boundary values of interest
            // if not, it would be invalid and therefore is not included in
            // the grid
            if (mean_at_stage - (3+4*log(16.0/j)) < parameters.at(i*2+2) 
                && mean_at_stage - (3+4*log(16.0/j)) > parameters.at(i*2+1))
            {
                tempvector.push_back(mean_at_stage-(3+4*log(16.0/j)));
            }
        }
        
        // these are the next 79 grid points
        for (j = 16; j <= 5*16; j++)
        {
            if (mean_at_stage-(3.0-3*(j-16.0)/(2*16.0)) < parameters.at(i*2+2) 
                && mean_at_stage-(3.0-3*(j-16.0)/(2*16.0)) > parameters.at(i*2+1))
            {
                tempvector.push_back(mean_at_stage-(3.0-3*(j-16.0)/(2*16.0)));
            }
        }
        
        // these are the last 15 grid points
        for (j = 5*16+1; j <= 6*16-1; j++)
        {
            if (mean_at_stage+(3.0+4*log(16.0/(6*16-j))) < parameters.at(i*2+2) 
                && mean_at_stage+(3.0+4*log(16.0/(6*16-j)))>parameters.at(i*2+1))
            {
                tempvector.push_back(mean_at_stage+(3.0+4*log(16.0/(6*16-j))));
            }
        }
        
        // add the last boundary value to the grid of points
        tempvector.push_back(parameters.at(i*2+2));

        // fill our grid with the temporary vector
        x.push_back(tempvector);
    }
    
    // to integrate from -inf to inf, 12r-3 grid points are used. Recall r is 
    // defined as 16 above. The odd numbered grid points were defined above in
    // the vector x. The final z vector will include the even numbered grid
    // points as the midpoints. For example, if x = {1, 2, 3}, then temp would
    // be {1.5, 2.5} and the full z vector {1, 1.5, 2, 2.5, 3}.
    std::vector<std::vector<double>> z;
    
    for (i = 0; i < x.size(); i++)
    {
        tempvector.clear();
        
        for (size_t j = 0; j < x.at(i).size()-1; j++)
        {
            tempvector.push_back(x.at(i).at(j));
            tempvector.push_back((x.at(i).at(j)+x.at(i).at(j+1))/2);
        }
        
        tempvector.push_back(x.at(i).at(x.at(i).size()-1));
        z.push_back(tempvector);

    }
    
    // the weights are calculated based on equation 19.10
    // quadrature approximation is used based on Simpson's rule
    std::vector<std::vector<double>> weights;
    
    for (i = 0; i < z.size();  i++)
    {
        // the first weight
        tempvector.clear();
        tempvector.push_back((z.at(i).at(2)-z.at(i).at(0))/6);
        
        for (size_t j = 2; j <= z.at(i).size() - 1; j++)
        {
            // for even numbered weights after the first weight
            if (j % 2 == 0)
            {
                tempvector.push_back(4.0*(z.at(i).at(j)-z.at(i).at(j-2))/6);
            }
            
            // for odd numbered weights after the first weight
            else
            {
                tempvector.push_back((z.at(i).at(j+1)-z.at(i).at(j-3))/6);
            }
        }
        
        // the last weight
        tempvector.push_back((z.at(i).at(z.at(i).size()-1)-z.at(i).at(z.at(i).size()-3))/6);
        weights.push_back(tempvector);

    }
    
    // h is the vector of k-1 dimensions (k = num stages) that collects the 
    // elements of a sum of for quick calculation of integrals between the 
    // z grid points defined above
    std::vector<std::vector<double>> h;
    
    size_t k;
    
    for (i = 0; i < z.size(); i++)
    {
        tempvector.clear();
        
        double info_k = information((static_cast<double>(i)+1)*parameters.at(0),sigma); 
        double info_kminus1 =information(static_cast<double>(i)*parameters.at(0),sigma);
        double delta_k = info_k - info_kminus1;

        if (i == 0)
        {
            for (size_t j = 0; j < z.at(i).size(); j++)
            {
                // f_1(z_1 | sigma) just before equation 19.4
                tempvector.push_back(
                    weights.at(i).at(j)*normal_pdf(z.at(i).at(j)-delta0*sqrt(info_k))
                );
            }
        }
        
        else
        {
            for (size_t j = 0; j < z.at(i).size(); j++)
            {
                tempvector.push_back(0);
                
                for (k = 0; k < z.at(i-1).size(); k++)
                {
                    tempvector.at(j) += 
                        // h_k-1(i_k-1 | theta)
                        h.at(i-1).at(k)
                        // w_k(i_k)
                        * weights.at(i).at(j)
                        // equation 19.4
                        * (sqrt(info_k)/sqrt(delta_k))
                        * normal_pdf(
                            // term 1
                            (z.at(i).at(j)*sqrt(info_k)
                            // term 2
                            - z.at(i-1).at(k)*sqrt(info_kminus1)
                            // term 3
                            - delta0*(delta_k))
                            // divided by
                            / (sqrt(delta_k))
                        );
                }
            }
        }
        
        h.push_back(tempvector);

    }
    
    // phi gives the probability of stopping for efficacy at each stage
    std::vector<double> phi;
    std::vector<double> psi;

    // this is being used to calculate the probabilities from the h vectors
    // it is taking two of the same delta values because its using the trick
    // discussed after equation 19.13
    converthtophi(h, z, phi, parameters, delta0, delta0, sigma);
    
    //calculate typeIerror by summing up phi:
    *typeIerror = 0;
    
    for(i = 0; i < phi.size(); i++)
    {
        *typeIerror += phi.at(i);
    }
    
    converthtopsi(h, z, psi, parameters, delta0, delta0, sigma);
    
    *expected_sample_size_null = expected_sample_size(phi, psi, parameters);
    
    converthtophi(h, z, phi, parameters, delta0, delta1, sigma);
    
    *power = 0;
    
    for(i = 0; i < phi.size(); i++)
    {
        *power += phi.at(i);
    }

    converthtopsi(h, z, psi, parameters, delta0, delta1, sigma);
    
    *expected_sample_size_crd = expected_sample_size(phi, psi, parameters);
    
    double deltaminimax;
    
    if(checkdm == 1)
    {
        finddeltaminimax_seq(
            h, z, parameters, delta0, delta1, sigma,
            &deltaminimax, expected_sample_size_dm
        );

        *worstcasedelta=deltaminimax;
    }

}


double functionvalue_deltaminimax(
        std::vector<double>& candidateparameters,
        double delta0,
        double delta1,
        double sigma,
        [[maybe_unused]] double K,
        double required_typeIerror,
        double required_typeIIerror,
        double penaltyparameter,
        int numberrestarts)
{
    double typeIerror;
    double power;
    double expected_sample_size_null;
    double expected_sample_size_crd;
    double worstcasedelta;
    double expected_sample_size_dm;
    double functionvalue=0;

    trialproperties_seq(
        candidateparameters,
        delta0,
        delta1,
        sigma,
        &typeIerror,
        &power,
        &expected_sample_size_null,
        &expected_sample_size_crd,
        &worstcasedelta,
        &expected_sample_size_dm,
        1
    );
    
    if (typeIerror > required_typeIerror)
    {
        functionvalue += (penaltyparameter 
                          + (typeIerror-required_typeIerror)/required_typeIerror)
                          * penaltyparameter;
    }
    
    if ((1-power) > required_typeIIerror)
    {
        functionvalue += penaltyparameter
                         + (((1-power)-required_typeIIerror)/required_typeIIerror)
                         * penaltyparameter;
    }
    
    if ((typeIerror>required_typeIerror || (1-power) > required_typeIIerror) && numberrestarts >= (-1))
    {
        functionvalue += penaltyparameter/10;
    }
    
    functionvalue += expected_sample_size_dm;
    
    return(functionvalue); 

}

double checkdesignconstraints(std::vector<double>& design)
{
    double validdesign {1};
    size_t numberstages = (design.size()-1)/2,i;
    
    // check that first efficacy parameter is more than futility parameter
    if (design.at(1) >= design.at(2))
    {
        validdesign=0;
    }
    
    for (i = 1; i < numberstages - 1; i++)
    {
        if (design.at(i*2+1) >= design.at(i*2+2))
        {
            validdesign = 0;
        }
        
        if (design.at(i*2+1) < design.at(i*2-1))
        {
            validdesign = 0;
        }
        
        if (design.at(i*2+2) > design.at(i*2))
        {
            validdesign = 0;
        }
    }
    
    if (design.at(numberstages*2) > design.at((numberstages-1)*2))
    {
        validdesign=0;
    }
    
    return validdesign;

}    


double generatenormalrandomvariable()
{
    double u1{};
    double u2{};

    u1 = uniform_random_01();
    u2 = uniform_random_01();
    
    return sqrt(-2 * log(u1)) * cos(2 * M_PI * u2);
}


void generatecandidatestate_deltaminimax(
        std::vector<double>& currentparameters,
        std::vector<double>& candidateparameters,
        std::vector<double>& lowerranges,
        std::vector<double>& upperranges,
        std::vector<double>& parametersigmas,
        int fixsamplesize)
{
    // for each candidate generation, pick one stage, and perturb that stage's 
    // parameters and the sample size per stage

    size_t i{};
    double u{};
    double temp{};
    [[maybe_unused]] double y{};

    candidateparameters = currentparameters;

    u = uniform_random_01();
    
    size_t numberofstages = (currentparameters.size() - 1)/2;
    
    double temp_stagetochange = floor(static_cast<double>(numberofstages) * u);
    
    size_t stagetochange = static_cast<size_t>(temp_stagetochange);
    
    if (stagetochange == (numberofstages - 1))
    {
        
        candidateparameters = currentparameters;
        // perturb sample size and last stage threshold:
        
        if (fixsamplesize == 0)
        {
            i = 0;
            do
            {
                temp=generatenormalrandomvariable();
                temp=temp*parametersigmas.at(i);
                candidateparameters.at(i)=temp+currentparameters.at(i);
            }
            while(candidateparameters.at(i)>=upperranges.at(i) || candidateparameters.at(i)<=lowerranges.at(i));
        }
        
        i = stagetochange * 2 + 1;
        do
        {
            temp = generatenormalrandomvariable();
            temp = temp * parametersigmas.at(i);
            candidateparameters.at(i) = temp + currentparameters.at(i);
            candidateparameters.at(i+1) = candidateparameters.at(i);
        }
        while((candidateparameters.at(i) >= upperranges.at(i) || candidateparameters.at(i) <= lowerranges.at(i)) || checkdesignconstraints(candidateparameters) == 0);
    }
    
    else
    {
        do
        {
            candidateparameters = currentparameters;
            
            // perturb sample size and last stage threshold:
            if (fixsamplesize == 0)
            {
                i = 0;
                do
                {
                    temp=generatenormalrandomvariable();
                    temp=temp*parametersigmas.at(i);
                    candidateparameters.at(i)=temp+currentparameters.at(i);
                }
                while(candidateparameters.at(i)>=upperranges.at(i) || candidateparameters.at(i)<=lowerranges.at(i));
            }
            
            i = stagetochange * 2 + 1;
            do
            {
                temp = generatenormalrandomvariable();
                temp = temp * parametersigmas.at(i);
                candidateparameters.at(i) = temp + currentparameters.at(i);
            }
            while(candidateparameters.at(i) >= upperranges.at(i) || candidateparameters.at(i) <= lowerranges.at(i));
      
            i = stagetochange * 2 + 2;
            do
            {
                temp=generatenormalrandomvariable();
                temp=temp*parametersigmas.at(i);
                candidateparameters.at(i)=temp+currentparameters.at(i);
            }
            while(candidateparameters.at(i) >= upperranges.at(i) || candidateparameters.at(i) <= lowerranges.at(i));
        }
        while(checkdesignconstraints(candidateparameters) == 0);
    }

}


void simulatedannealing_deltaminimax(
        double delta0,
        double delta1,
        double sigma,
        double K,
        double requiredtypeIerror,
        double requiredpower,
        std::vector<double> &initialparameters,
        std::vector<double> lowerranges,
        std::vector<double> upperranges,
        std::vector<double>& initialparameterssigma,
        double initialcosttemperature,
        double finalparametersigma,
        double finalcosttemperature,
        int numbercandidategenerationsperrestart,
        int minnumberrestarts,
        std::vector<double> &finalparameters,
        double *finalfunctionvalue,
        double penaltyparameter)
{
    size_t i;
    std::vector<double> currentparameters = initialparameters;
    
    double newfunctionvalue;

    double minimumfunctionvalue = functionvalue_deltaminimax(
        initialparameters,
        delta0,
        delta1,
        sigma,
        K,
        requiredtypeIerror,
        (1-requiredpower),
        penaltyparameter,
        -2 // last parameter is number of restarts
    );
        
    double x;
    double numbersincereduction=0;
    double currentfunctionvalue;
    double reductioninfunctionvalue;
    
    std::vector<double> parametersigmas;
    std::vector<double> minimumparameters = currentparameters;
    std::vector<double> candidateparameters;

    parametersigmas = initialparameterssigma;
    int numberrestarts {0};
    
    double previousrestart;
    double candidategenerations {0};
    double costtemperature = initialcosttemperature;
    double rhocost = pow(finalcosttemperature/initialcosttemperature, 1.0/numbercandidategenerationsperrestart);
    double rhosigma = pow(finalparametersigma/parametersigmas.at(0), 1.0/numbercandidategenerationsperrestart);
    
    [[maybe_unused]] double minimumloss;
    
    do
    {
        generatecandidatestate_deltaminimax(
            currentparameters,
            candidateparameters,
            lowerranges,
            upperranges,
            parametersigmas,
            0
        );
        
        newfunctionvalue = functionvalue_deltaminimax(
            candidateparameters,
            delta0,
            delta1,
            sigma,
            K,
            requiredtypeIerror,
            (1-requiredpower),
            penaltyparameter,
            numberrestarts-minnumberrestarts
        );
            
            for(i=0;i<parametersigmas.size();i++)
            {
                parametersigmas.at(i) *= rhosigma;
            }
            
            x = uniform_random_01();
            
            candidategenerations++;
            
            if (exp(-(newfunctionvalue - currentfunctionvalue)/costtemperature) > x)
            {
                currentfunctionvalue = newfunctionvalue;
                costtemperature *= rhocost;
                currentparameters = candidateparameters;
                
                if (newfunctionvalue < minimumfunctionvalue)
                {
                    minimumparameters = currentparameters;
                    minimumfunctionvalue = newfunctionvalue;
                    numbersincereduction = 0;
                }
                
                else
                {
                    numbersincereduction++;
                }
            }
            
            else
            {
                numbersincereduction++;
            }
            
            if (static_cast<int>(numbersincereduction) % 25 == 0)
            {
                currentparameters = minimumparameters;
                currentfunctionvalue = minimumfunctionvalue;
            }
            
            if(candidategenerations >= numbercandidategenerationsperrestart)
            {
                //reset temperature
                currentparameters = minimumparameters;
                currentfunctionvalue = minimumfunctionvalue;
                costtemperature = initialcosttemperature;
                rhocost = pow(finalcosttemperature/initialcosttemperature, 1.0/numbercandidategenerationsperrestart);
                parametersigmas = initialparameterssigma;
                rhosigma = pow(finalparametersigma/parametersigmas.at(0), 1.0/numbercandidategenerationsperrestart);
                
                candidategenerations = 0;
                numberrestarts++;
                
                std::cout << "Restart " << numberrestarts << ", function value = " << minimumfunctionvalue << "\n";
                reductioninfunctionvalue = previousrestart - minimumfunctionvalue;
                previousrestart = minimumfunctionvalue;
            }
        }
        while(numberrestarts<=minnumberrestarts || reductioninfunctionvalue>0.005);
        
        minimumparameters.at(0) = floor(minimumparameters.at(0));
        minimumfunctionvalue = functionvalue_deltaminimax(
            minimumparameters,
            delta0,
            delta1,
            sigma,
            K,
            requiredtypeIerror,
            (1-requiredpower),
            penaltyparameter,
            1
        );

        currentfunctionvalue=minimumfunctionvalue;
        currentparameters=minimumparameters;
        
        // repeat, but fixing samplesize
        candidategenerations = 0;
        numberrestarts -= 4;
        
        do
        {
            generatecandidatestate_deltaminimax(
                currentparameters,
                candidateparameters,
                lowerranges,
                upperranges,
                parametersigmas,
                1
            );
                
            newfunctionvalue = functionvalue_deltaminimax(
                candidateparameters,
                delta0,
                delta1,
                sigma,
                K,
                requiredtypeIerror,
                (1-requiredpower),
                penaltyparameter,
                1
            );
            
            // cout<<minimumfunctionvalue<<" "<<newfunctionvalue<<"\n";
            for (i = 0; i < parametersigmas.size(); i++)
            {
                parametersigmas.at(i) *= rhosigma;
            }
            
            x = uniform_random_01();
            
            candidategenerations++;
            
            if (exp(-(newfunctionvalue-currentfunctionvalue)/costtemperature) > x)
            {
                currentfunctionvalue = newfunctionvalue;
                costtemperature *= rhocost;
                currentparameters = candidateparameters;
                
                if (newfunctionvalue < minimumfunctionvalue)
                {
                    minimumparameters = currentparameters;
                    minimumfunctionvalue = newfunctionvalue;
                    numbersincereduction = 0;
                }
                
                else
                {
                    numbersincereduction++;
                }
            }
            
            else
            {
                numbersincereduction++;
            }
            
            if (static_cast<int>(numbersincereduction) % 10 == 0)
            {
                currentparameters = minimumparameters;
                currentfunctionvalue = minimumfunctionvalue;
            }
            
            if (candidategenerations >= numbercandidategenerationsperrestart)
            {
                //reset temperature
                currentparameters = minimumparameters;
                currentfunctionvalue = minimumfunctionvalue;
                costtemperature = initialcosttemperature;
                
                rhocost = pow(finalcosttemperature/initialcosttemperature, 1.0/numbercandidategenerationsperrestart);
                parametersigmas = initialparameterssigma;
                
                rhosigma = pow(finalparametersigma/parametersigmas.at(0), 1.0/numbercandidategenerationsperrestart);
                candidategenerations = 0;
                numberrestarts++;
                
                std::cout << "Restart " << numberrestarts << ", function value = " << minimumfunctionvalue << "\n";
                reductioninfunctionvalue = previousrestart - minimumfunctionvalue;
                
                minimumfunctionvalue = functionvalue_deltaminimax(
                    minimumparameters,
                    delta0,
                    delta1,
                    sigma,
                    K,
                    requiredtypeIerror,
                    (1-requiredpower),
                    penaltyparameter,
                    numberrestarts - minnumberrestarts
                );
                    
                previousrestart = minimumfunctionvalue;
            
            }

    } while (numberrestarts <= minnumberrestarts || reductioninfunctionvalue > 0);
  
    finalparameters = minimumparameters;
    *finalfunctionvalue = minimumfunctionvalue;

}


int main(int argc, char *argv[])
{
    if(argc != 8)
    {
        std::cout<<"Usage: ./finddeltaminimaxdesign <delta0> <delta1> <sigma> <typeIerror> <power> <number of stages> <outfile>\n";
        return 0;
    }
    
    // pull all the values from the user input
    double delta0 = atof(argv[1]);
    double delta1 = atof(argv[2]);
    double initialsigma = atof(argv[3]);
    double requiredtypeIerror = atof(argv[4]);
    double requiredpower = atof(argv[5]);
    int K = atoi(argv[6]);
    std::string outfilename = argv[7];
    
    //set initial seed:
    time_t seed = time(0);
    time_t i;
    [[maybe_unused]] int j;
    
    for (i = 0; i < seed % 10000; i++)
    {
        uniform_random_01();
    }

    std::cout << "Seed = " << seed << "\n";
    
    // standardise problem:
    double delta = (delta1-delta0)/initialsigma;
    double sigma = 1;

    double singlestagesamplesize = one_stage_sample_size(
        delta,
        sigma,
        requiredtypeIerror,
        (1-requiredpower),
        1
    );
    
    double typeIerror;
    double power;
    double expected_sample_size_null;
    double expected_sample_size_crd;
    double worstcasedelta;
    double expected_sample_size_dm;
    
    std::vector<double> parameters;
    std::vector<double> currentparameters;
    std::vector<double> candidateparameters;
    std::vector<double> lowerranges;
    std::vector<double> upperranges;
    std::vector<double> parametersigmas;
    std::vector<double> initialparametersigmas;
    
    find_triangular_design(
        0,
        delta,
        sigma,
        K,
        requiredtypeIerror * 49/50,
        (1-requiredpower),
        parameters
    );
    
    // find trial properties of triangular design
    trialproperties_seq(
        parameters,
        0,
        delta,
        sigma,
        &typeIerror,
        &power,
        &expected_sample_size_null,
        &expected_sample_size_crd,
        &worstcasedelta,
        &expected_sample_size_dm,
        1
    );
    
    // set lower ranges for parameters in simulated annealing
    lowerranges.push_back(2);
    upperranges.push_back(singlestagesamplesize);
    
    initialparametersigmas.push_back(singlestagesamplesize/5);
    for (i = 0; i < K; i++)
    {
        lowerranges.push_back(-4);
        upperranges.push_back(4);
        lowerranges.push_back(-4);
        upperranges.push_back(4);
        
        initialparametersigmas.push_back(3);
        initialparametersigmas.push_back(3);
    }
    
    std::vector<double> initialparameters = parameters;
    std::vector<double> finalparameters;
    
    double finalfunctionvalue;
    
    // DEBUG
    for (auto num : initialparameters)
        std::cout << num << " ";

    // DEBUG
    std::cout << "\n";

    // carries out simulated annealing to find sample size and stopping
    // boundaries for delta minimax design. First, the process allows n to be
    // non-integer, searching over the sample size and stopping boundaries.
    // After, the sample size is rounded to the nearest integer, and the 
    // stopping boundaries only are searched over.
    simulatedannealing_deltaminimax(
        0,
        delta,
        sigma,
        K,
        requiredtypeIerror,
        requiredpower,
        initialparameters,
        lowerranges,
        upperranges,
        initialparametersigmas,
        100,
        0.005,
        0.005,
        10000,
        5,
        finalparameters,
        &finalfunctionvalue,
        singlestagesamplesize
    );
    
    trialproperties_seq(
        finalparameters,
        0,
        delta,
        sigma,
        &typeIerror,
        &power,
        &expected_sample_size_null,
        &expected_sample_size_crd,
        &worstcasedelta,
        &expected_sample_size_dm,
        1
    );
    
    // write results to file with specified name
    std::ofstream outfile;
    outfile.open(outfilename.c_str(), std::ios_base::app);
    
    outfile << requiredtypeIerror << " " << requiredpower << " " << K 
            << " " << seed << " " << typeIerror << " " << power << " " 
            << expected_sample_size_null << " " << expected_sample_size_crd
            << " " << expected_sample_size_dm << " ";
            
    for(size_t i = 0; i < finalparameters.size(); i++)
    {
        outfile << finalparameters.at(i) << " ";
    }
    
    outfile << "\n";
    outfile.close();
    
    return 0;
}
